= adjust: Adjust VLBI clocks for correlation
E. Himwich, B. Corey, M. Titus
Version 0.2 - July 2020

== Installation

. Requires pip3 (alternatively instead of the `bash install` command, replace the _shebang_ line in `adjust.py` with what your system needs):

    git clone https://github.com/whi-llc/adjust
    cd adjust
    bash install

. Add the directory where it was installed to your `PATH` variable

== Usage

For help:

    adjust -h

Output:
....
Usage: adjust -afhvx: file
  finds average offset to apply to correlator 'Used' clocks
  after finding average offset, use -a to print adjusted offsets
     file:
         one line per station (three fields minimum, blank delimited):
               two-letter station, case sensitive, e.g. Ht
               fmout-gps
               Used
               Additional columns ignored.
     output, unless -a specified:
         one line per station:
               station
               peculiar offset
               difference from historical
               "x" excluded or " " included
               residual to fit for Diff_mean
               Normalized residual for std
               Normalized residual for historical RMS
               station's historical offset
               station's historical RMS
               number of data points in history
        two lines: explanation
        one line: peculiar offsets version
        one line: summary
               number of stations included
               total number of stations
               average offset (Diff_mean)
               std
     output, with -a specified:
         one line per station:
               station
               Use flag
                 i=included
                 x=excluded
                 n=new
               Adjusted peculiar offset
               File name (all the same)
 
Options:
 -a   print adjusted peculiar offsets
 -b   use broadband peculiar offsets
 -f   sub 8 us from Ft fmout for 512 Mbps
 -h   this text
 -v   print version number
 -x   stations to exclude
        list of two letter codes, colon separated, case sensitive
 -z   accept zero values
....

== DRAFT:

=== Files

All data files are in the `data/` sub-directory

. File types
+
.. Files `+++*++++++_+++po+++_++++++*+++.dat` are peculiar offset (PO) data
+
.. Files `+++*++++++_+++sd+++_++++++*+++.dat` are sampler delay (SD) data
+
.. Other files are other information and plots.

. `bb` files are for broadband (VGOS)

.. Version numbers are of the form `vS.P` where:

... `S` is the sampler delay (SD) version
... `P` is the peculiar offset (PO) version
...  PO and SD files are related by the `S` value
+
`P` changes more quickly than `S`, so there can be multiple `P` values for a given `S`

.. SD files:
+
`bb+++_+++sd+++_+++_v_.dat`, where `v` is of the form vS: the `S`-th SDs
+
.. PO files:
+
`bb_po_v.dat`, where `v` is of the form `vS.P`: the `P`-th POs for the `S`-th SDs

. `sx` files are S/X
+
.. PO files:
+
`sx_po_v.dat`, where `v` is of the form `vN`

. The symbolic links: `bb_po.dat`, `bb_sd.dat`, and `sx_po.dat` point to the current versions.

=== Plans:

. Modify adjust to read the PO data from the linked file in `data/`.
. Add `-d` option to select a specific PO version
. Add `-u` option to adjust to print new final values based on adjustment

=== Longer term possibilities:

. Modify `-u` option to print final values as `clock_early` statements using
   `clock_early` statements as input.
. Modify input to read `fmout-gps` values from `clock_early` statements (extension to VEX)
. Add option to apply a fixed offset final values (adjusted values as well?)
. Change PO files to use `.py` instead of `.dat` since they are Python code.
